In [50]:
import pandas as pd
import numpy as np
import random
from matplotlib import pyplot as plt
import math
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [153]:
data = pd.read_csv("./iris.csv")
data.columns = ["len","width","flen","fwidth","species"]
data.describe()
x = data.drop(['species'],axis=1)
y = data['species']

In [188]:
x.shape

(149, 4)

In [191]:
x_train, x_test ,y_train, y_test = train_test_split(x,y,test_size = 0.33,random_state = 42)

In [192]:
y_train.shape

(99,)

In [193]:
x_train.describe()
Norm = Normalizer(norm="l2")
y_test.describe()

count              50
unique              3
top       Iris-setosa
freq               19
Name: species, dtype: object

In [194]:
x_train = Norm.transform(x_train)
x_test = Norm.transform(x_test)
change = {'Iris-setosa':0, 'Iris-versicolor':1,'Iris-virginica':2}
# y_train.replace(change,inplace = True)
# y_test.replace(change,inplace=True)
y_train = LabelEncoder().fit_transform(np.array(y_train))
y_train = OneHotEncoder(sparse=False).fit_transform(y_train.reshape((-1,1)))
y_test = LabelEncoder().fit_transform(np.array(y_test))
y_test = OneHotEncoder(sparse=False).fit_transform(y_test.reshape((-1,1)))

In [195]:
y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0

对我们的数据进行归一化的处理

In [196]:
from keras.preprocessing.text import Tokenizer
from keras import models
from keras import layers

In [164]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [215]:
network = models.Sequential()
network.add(layers.Dense(units= 16, activation = "relu",input_shape = [4]))
#network.add(layers.Dense(units = 1, activation = "sigmoid"))
network.compile(loss = "binary_crossentropy", optimizer = "rmsprop",metrics = ["accuracy"])


In [219]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D, Flatten
# 构建神经网络
from tensorflow.keras.utils import to_categorical 
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
model = Sequential()
# 全连接层一
model.add(Flatten())
# model.add(Dense(1024))
model.add(Activation('relu'))

# 全连接层二
# model.add(Dense(10))
# model.add(Activation('softmax'))

# 选择并定义优化求解方法
#adam = Adam(lr = 1e-4)

# 选择损失函数、求解方法、度量方法
model.compile(loss = 'categorical_crossentropy', metrics = ['accuracy'])

# # 训练模型
model.fit(x_train, y_train, epochs = 2, batch_size = 32)

# # 评估模型
# loss, accuracy = model.evaluate(x_test, y_test)


Epoch 1/2


ValueError: in user code:

    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 809, in train_step
        loss = self.compiled_loss(
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/losses.py", line 1664, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/backend.py", line 4994, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 3, 3, 3, 3, 3, 3, 3, 2) and (None, 4) are incompatible


In [205]:
x_test.shape

(50, 4)

In [203]:
his = network.fit(x_train,y_train,epochs=300,verbose=0,batch_size = 100,validation_data=(x_test,y_test))

ValueError: in user code:

    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 809, in train_step
        loss = self.compiled_loss(
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/losses.py", line 1807, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/opt/anaconda3/lib/python3.8/site-packages/keras/backend.py", line 5173, in binary_crossentropy
        bce = target * tf.math.log(output + epsilon())

    ValueError: Dimensions must be equal, but are 3 and 16 for '{{node binary_crossentropy/mul}} = Mul[T=DT_FLOAT](IteratorGetNext:1, binary_crossentropy/Log)' with input shapes: [?,3], [?,16].


In [125]:
predict_y = network.predict(x_test)

In [120]:
loss, accuracy = network.evaluate(x_test, y_test)

1/1 [==============================] - 0s 22ms/step - loss: 0.2534 - accuracy: 0.4000


In [99]:
x.size

596

In [100]:
x_trian.size

396

In [122]:
y_test.value_counts()

1    6
0    6
2    3
Name: species, dtype: int64

In [126]:
predict_y

array([[0.9979203 ],
       [0.98110497],
       [0.99908143],
       [0.9974699 ],
       [0.9984226 ],
       [0.97539914],
       [0.99784714],
       [0.99871814],
       [0.997996  ],
       [0.99864775],
       [0.998533  ],
       [0.97883606],
       [0.98448145],
       [0.9817308 ],
       [0.9858914 ]], dtype=float32)